nodeLinker: node-modules

packageExtensions:
  "@cypress/code-coverage@*":
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      babel-loader: "*"
      webpack: "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
